version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./provisioning/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:

      - client


      - server



  client:
    build: .
    volumes:
      - .:/code
    command: npm run client:watch -- --host 0.0.0.0 --port 8080
    ports:
      - 8001:8080
      - 35729:35729



  server:
    build: .
    volumes:
      - .:/code
#    depends_on:
#      - postgresql
#      - mongodb
#      - elasticsearch
    command: npm run server:watch
    ports:
      - '9229:9229'

###
# Postgresql configuration
###
#
#  postgresql:
#    image: postgres:9.5.5
#    environment:
#      - POSTGRES_USER=blink
#      - POSTGRES_PASSWORD=blink
#      - POSTGRES_DB=blink
#
###

###
# Mongodb configuration
###
#
#  mongodb:
#    image: mongo
#
###

###
# Elasticsearch configuration
###
#
#  elasticsearch:
#    image: elasticsearch
#
###

